version: '2'

services:
  postgres:
    restart: always
    image: cbihcity/pg
    container_name: pg
    ports:
      - "5432:5432"
  simple-jpa-ap:
    restart: always
    image: cbihcity/simple-jpa-ap
    container_name: simple
    links:
      - postgres
    ports:
      - "8090:8090"
  mongo_db:
        restart: always
        image: mongo
        container_name: mongo_db
        ports:
          - "27017:27017"
  simple-nosql-ap:
      restart: always
      image: cbihcity/mongo-app
      container_name: mongo_app
      links:
        - mongo_db
      ports:
        - "1111:1111"